name: env_banner
description: A simple widget that helps you place a banner on any widget.
version: 1.0.0+2
homepage: https://github.com/melvinsalas/env_banner
issue_tracker: https://github.com/melvinsalas/env_banner/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
